name: Tag and release

on:
   push:
      branches:
         - main

permissions:
   contents: write
   pull-requests: read

jobs:
   tag-and-release:
      runs-on: ubuntu-latest
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
         - name: Tag/Release on Push Action
           uses: rymndhng/release-on-push-action@v0.27.0
           with:
              bump_version_scheme: minor
